version: '3'

services:

  ngnix:
    container_name: ngnix
    image: nginx:1.13.11
    ports:
      - 1443:1443
    volumes:
      - "./shared/ngnix/config/nginx.conf:/etc/nginx/nginx.conf"
      - "./shared/ngnix/certs:/run/secrets"
    networks:
      - tlabs-net

  service-a:
    container_name: service-a
    build:
      context: ./tlabs-comm-grpc-service-a/
      args:
        JAR_FILE: target/*.jar
    volumes:
      - "./shared/a/certs:/certs"
    networks:
      - tlabs-net

  service-b1:
    container_name: service-b1
    build:
      context: ./tlabs-comm-grpc-service-b/
      args:
        JAR_FILE: target/*.jar
    volumes:
      - "./shared/b/certs:/certs"
    networks:
      - tlabs-net

  service-b2:
    container_name: service-b2
    build:
      context: ./tlabs-comm-grpc-service-b/
      args:
        JAR_FILE: target/*.jar
    volumes:
      - "./shared/b/certs:/certs"
    networks:
      - tlabs-net

  service-b3:
    container_name: service-b3
    build:
      context: ./tlabs-comm-grpc-service-b/
      args:
        JAR_FILE: target/*.jar
    volumes:
      - "./shared/b/certs:/certs"
    networks:
      - tlabs-net

networks:
  tlabs-net: {}